#!/bin/sh /etc/rc.common
#
# Copyright (C) 2017 openwrt-system-monitor
#
# This is free software, licensed under the GNU General Public License v3.
# See /LICENSE for more information.
#
START=99
STOP=15
NAME=sysmonitor
APP_PATH=/usr/share/$NAME

start()
{
	[ $(ps |grep ttyd|grep -v grep|wc -l) == 0 ] && /usr/bin/ttyd -6 /bin/login &
	if [ -f "/etc/init.d/ddns" ]; then
		if [ $(uci get sysmonitor.sysmonitor.ddns) == 1 ];  then
			/etc/init.d/ddns enable
			if [ $(ps |grep ddns|grep -v grep|wc -l) == 0 ]; then
				/etc/init.d/ddns start
			fi
		else
			/etc/init.d/ddns disable
			/etc/init.d/ddns stop
		fi
	fi
#	$APP_PATH/sysapp.sh vpn
	if [ -f "/etc/init.d/smartdns" ]; then
		sed -i s/"#conf-file"/"conf-file"/ /etc/smartdns/custom.conf
		[ $(uci get sysmonitor.sysmonitor.smartdnsAD) == 0 ] && sed -i s/"conf-file"/"#conf-file"/ /etc/smartdns/custom.conf
		[ -f /tmp/smartdns.cache ] && rm /tmp/smartdns.cache
		if [ $(uci get sysmonitor.sysmonitor.smartdns) == 1 ];  then
			uci set smartdns.@smartdns[0].enabled='1'
			uci set smartdns.@smartdns[0].seconddns_enabled='0'
			uci set smartdns.@smartdns[0].port=$(uci get sysmonitor.sysmonitor.smartdnsPORT)
			uci commit smartdns
			/etc/init.d/smartdns start

		else
			/etc/init.d/smartdns stop >/dev/null 2>&1
		fi
	fi
	$APP_PATH/sysapp.sh getip
	$APP_PATH/sysapp.sh setdns
#	uci set sysmonitor.sysmonitor.enable=1
#	uci commit sysmonitor
	$APP_PATH/sysmonitor.sh &
}


