#!/bin/sh /etc/rc.common
#
# Copyright (C) 2017 openwrt-system-monitor
#
# This is free software, licensed under the GNU General Public License v3.
# See /LICENSE for more information.
#
START=99
STOP=15
NAME=sysmonitor
APP_PATH=/usr/share/$NAME

stop()
{
	set sysmonitor.sysmonitor.enable=0
	set commit sysmonitor
}
start()
{
	[ $(ps |grep ttyd|grep -v grep|wc -l) == 0 ] && /usr/bin/ttyd -6 /bin/login &
	if [ -f "/etc/init.d/ddns" ]; then
		if [ $(uci get sysmonitor.sysmonitor.ddns) == 1 ];  then
			/etc/init.d/ddns enable
			if [ $(ps |grep ddns|grep -v grep|wc -l) == 0 ]; then
				/etc/init.d/ddns start
			fi
		else
			/etc/init.d/ddns disable
			/etc/init.d/ddns stop
		fi
	fi
	$APP_PATH/sysapp.sh vpn
	$APP_PATH/sysapp.sh getip
	set sysmonitor.sysmonitor.enable=1
	set commit sysmonitor
	$APP_PATH/sysmonitor.sh &
}


