#!/bin/sh

uci set smartdns.@smartdns[0].enabled='1'
uci commit smartdns

uci set fstab.@global[0].anon_mount='1'
uci commit fstab

#sed -i '/internal_iface/d' /etc/config/upnpd
#uci set upnpd.config.enabled='1'
#uci set upnpd.config.presentation_url='http://192.168.88.1'
#uci commit upnpd

uci set system.@system[0].hostname='VAIO'
uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Shanghai
uci commit system

#uci set dhcp.@dnsmasq[0].rebind_protection='0'
#uci del dhcp.lan.dhcp_option
#uci add_list dhcp.lan.dhcp_option='44,192.168.1.220'
uci set dhcp.lan.ra='relay'
uci set dhcp.lan.dhcpv6='relay'
uci set dhcp.lan.ndp='relay'
uci set dhcp.lan.ignore='0'
uci set dhcp.lan.master='0'
uci set dhcp.wan.ra='relay'
uci set dhcp.wan.dhcpv6='relay'
uci set dhcp.wan.ndp='relay'
uci set dhcp.wan.ignore='1'
uci set dhcp.wan.master='1'
uci set dhcp.@dnsmasq[0].localservice='0'
uci set dhcp.@dnsmasq[0].domainneeded='0'
uci set dhcp.@dnsmasq[0].rebind_localhost='0'
uci set dhcp.@dnsmasq[0].rebind_protection='0'
uci commit dhcp

cat >> /etc/config/dhcp <<EOF
config domain
	option name 'NAS'
	option ip '192.168.1.220'

config domain
	option name 'VPN'
	option ip '192.168.1.110'
EOF

uci set network.globals.ula_prefix=''
uci set network.@device[0].stp='1'
#uci set network.@device[0].MTU='1472'
homeip='192.168.1.1'
uci set network.wan.hostname="VAIOMI"
uci set network.wan.proto='static'
uci set network.wan.ipaddr='192.168.1.119'
uci set network.wan.netmask='255.255.255.0'
uci set network.wan.gateway=$homeip
uci del network.wan.dns
uci add_list network.wan.dns=$homeip
uci set network.wan.ifname='eth0.2'
uci set network.wan.force_link='1'
uci set network.wan.delegate='1'
uci set network.wan.type='bridge'
uci set network.wan6.ifname='br-wan'
uci set network.wan6.force_link='1'
uci set network.wan6.delegate='1'
uci set network.lan.stp='0'
uci set network.lan.igmp_snooping='0'
uci set network.lan.ip6assign='64'
uci set network.lan.ipaddr='192.168.88.1'
uci set network.lan.force_link='1'
uci set network.lan.delegate='1'
uci del network.lan.dns
uci add_list network.lan.dns='119.29.29.29'
uci add_list network.lan.dns='223.5.5.5'
uci add_list network.lan.dns='114.114.114.114'
uci commit network

uci set wireless.radio0.noscan='1'
#uci set wireless.radio0.country="CN"
uci set wireless.radio0.htmode='HT40'
uci set wireless.radio0.channel='8'
uci set wireless.radio0.legacy_rates='0'
#uci set wireless.radio0.mu_beamformer='1'
uci set wireless.default_radio0.ssid='VAIOMI'
uci set wireless.default_radio0.key='sonyvaiotz13w'
uci set wireless.default_radio0.encryption='psk-mixed'
uci set wireless.default_radio0.disassoc_low_ack='0'
#uci set wireless.default_radio0.disabled='1'

#uci set wireless.radio1.country="CN"
uci set wireless.radio1.hwmode='11a'
uci set wireless.radio1.htmode='VHT80'
uci set wireless.radio1.channel='44'
#uci set wireless.radio1.txpower='23'
uci set wireless.radio1.legacy_rates='0'
#uci set wireless.radio1.mu_beamformer='1'
uci set wireless.default_radio1.ssid='VAIOMI'
uci set wireless.default_radio1.key='sonyvaiotz13w'
uci set wireless.default_radio1.encryption='psk-mixed'
uci set wireless.default_radio1.disassoc_low_ack='0'
#uci set wireless.default_radio1.disabled='1'
uci commit wireless

uci set firewall.@defaults[0].flow_offloading='1'
uci set firewall.@defaults[0].flow_offloading_hw='1'
uci set firewall.@defaults[0].synflood_protect='1'
uci set firewall.@defaults[0].input='ACCEPT'
uci set firewall.@defaults[0].output='ACCEPT'
uci set firewall.@defaults[0].forward='REJECT'
uci set firewall.@zone[0].input='ACCEPT'
uci set firewall.@zone[0].output='ACCEPT'
uci set firewall.@zone[0].forward='ACCEPT'
uci set firewall.@zone[1].input='ACCEPT'
uci set firewall.@zone[1].output='ACCEPT'
uci set firewall.@zone[1].forward='REJECT'
uci commit firewall

cat /etc/config/firewall | grep wghome > /dev/null
if [ $? -ne 0 ];then
cat >> /etc/config/firewall <<EOF
config rule
	option dest_port '58888'
	option src 'wan'
	option name 'Wireguard'
	option target 'ACCEPT'
	option src_port '58888'

config zone
	option name 'wghome'
	option input 'ACCEPT'
	option forward 'ACCEPT'
	option output 'ACCEPT'
	option network 'wghome'

config forwarding
	option dest 'wan'
	option src 'wghome'
EOF
fi

file1='/etc/config/network'
temp=$(sed -n -e "/option name 'switch0'/=" $file1)
val1=`expr $temp - 1`
tmp=$val1',$d'
sed -i $tmp $file1

cat /etc/config/network | grep 192.168.9.119 > /dev/null
if [ $? -ne 0 ];then
cat >> /etc/config/network <<EOF
config switch
	option name 'switch0'
	option reset '1'
	option enable_vlan '1'

config switch_vlan
	option device 'switch0'
	option vlan '1'
	option vid '1'
	option ports '6t 1'

config switch_vlan
	option device 'switch0'
	option vlan '2'
	option vid '2'
	option ports '6t 3 2 4'

config interface 'wghome'
	option proto 'wireguard'
	option private_key 'eMglGU5RUxSQtOfL8Txg6Dych1491zZP1JjQR8flykI='
	list addresses '192.168.9.119'
	option listen_port '58888'

config wireguard_wghome
	option description 'ALiCloud'
	option persistent_keepalive '25'
	option endpoint_port '58888'
	list allowed_ips '192.168.9.0/24'
	option route_allowed_ips '1'
	option endpoint_host '47.100.183.141'
	option public_key 'GWLcAE1Of7H1iolrSRAK1FYGB5dhwbEMTZvEJxoZYGA='

config wireguard_wghome
	option public_key 'RuCdaOHKPDf2c2kihx2dzBhEDKZnbnhP1N4aUBkzw3A='
	option route_allowed_ips '1'
	list allowed_ips '192.168.9.11'
	option description 'Iphone8Plus'

config wireguard_wghome
	option public_key 'HkRSRzDMks74AmFQlnByouVNR6E/o5I+j033QqF1UyI='
	option route_allowed_ips '1'
	list allowed_ips '192.168.9.12'
	option description 'Iphone7'

config wireguard_wghome
	option public_key 'ql9g9ngGQMq9cyBaun5QjnyROyh7Cu4zJ9eZwFM6UGw='
	option route_allowed_ips '1'
	list allowed_ips '192.168.9.13'
	option description 'Iphone8'
EOF
fi

[ -f /etc/lighttpd/lighttpd.conf ] && {
file='/etc/lighttpd/lighttpd.conf'
sed -i  's|".php", ".pl", ".fcgi"|".php", ".pl", ".fcgi", ".lua"|' $file
sed -i  's|#server.port|server.port|' $file
}

[ -f /etc/lighttpd/conf.d/30-cgi.conf ] && {
sed -i '/".cgi" => "\/usr\/bin\/perl"/i\                               ".lua" => "\/usr\/bin\/lua",' /etc/lighttpd/conf.d/30-cgi.conf
sed -i '/".cgi" => "\/usr\/bin\/perl"/i\                               ".php" => "\/usr\/bin\/php-cgi",' /etc/lighttpd/conf.d/30-cgi.conf
cat >> /etc/lighttpd/conf.d/30-cgi.conf <<EOF
cgi.assign += ( "/cgi-bin/luci" => "",
                "/cgi-bin/cgi-backup" => "",
                "/cgi-bin/cgi-download" => "",
                "/cgi-bin/cgi-exec" => "",
                "/cgi-bin/cgi-upload" => "" )
				
server.username := ""
server.groupname := ""
EOF
}

[ -f /etc/init.d/ddns ] && {
cat > /etc/config/ddns <<EOF
config ddns 'global'
	option upd_privateip '1'

config service 'ChangeipECS'
	option service_name 'changeip.com'
	option enabled '1'
	option lookup_host 'ecs.freeddns.com'
	option domain 'ecs.freeddns.com'
	option username 'sqmshcn@gmail.com'
	option password 'sqmshcn110'
	option ip_source 'web'
	option ip_url 'http://47.100.183.141/ip.php'
	option interface 'lan'
	option force_dnstcp '1'

config service 'DynuVAIO'
	option service_name 'dynu.com'
	option enabled '1'
	option lookup_host 'vaiocn.ddnsfree.com'
	option domain 'vaiocn.ddnsfree.com'
	option username 'sqmshcn'
	option password 'dynuddns'
	option ip_source 'web'
	option ip_url 'http://members.3322.org/dyndns/getip'
	option interface 'lan'
	option force_dnstcp '1'

config service 'DynuHOME'
	option service_name 'dynu.com'
	option enabled '1'
	option lookup_host 'homecn.ddnsfree.com'
	option domain 'homecn.ddnsfree.com'
	option username 'sqmshcn'
	option password 'dynuddns'
	option ip_source 'web'
	option ip_url 'http://members.3322.org/dyndns/getip'
	option interface 'lan'
	option force_dnstcp '1'

config service 'DynuNAS'
	option service_name 'dynu.com'
	option enabled '1'
	option lookup_host 'nascn.ddnsfree.com'
	option domain 'nascn.ddnsfree.com'
	option username 'sqmshcn'
	option password 'dynuddns'
	option ip_source 'web'
	option ip_url 'http://members.3322.org/dyndns/getip'
	option interface 'lan'
	option force_dnstcp '1'

config service 'DynuSSR'
	option service_name 'dynu.com'
	option enabled '1'
	option lookup_host 'ssrcn.ddnsfree.com'
	option domain 'ssrcn.ddnsfree.com'
	option username 'sqmshcn'
	option password 'dynuddns'
	option ip_source 'web'
	option ip_url 'http://members.3322.org/dyndns/getip'
	option interface 'lan'
	option force_dnstcp '1'

config service 'DynuVAIO6'
	option service_name 'dynu.com'
	option enabled '1'
	option lookup_host 'vaiocn.ddnsfree.com'
	option domain 'vaiocn.ddnsfree.com'
	option username 'sqmshcn'
	option password 'dynuddns'
	option ip_source 'web'
	option ip_url 'http://192.168.1.120/ip6.html'
	option use_ipv6 '1'
	option interface 'lan'
	option force_dnstcp '1'

config service 'DynuHOME6'
	option service_name 'dynu.com'
	option enabled '1'
	option lookup_host 'homecn.ddnsfree.com'
	option domain 'homecn.ddnsfree.com'
	option username 'sqmshcn'
	option password 'dynuddns'
	option ip_source 'web'
	option ip_url 'http://192.168.1.119/ip6.html'
	option use_ipv6 '1'
	option interface 'lan'
	option force_dnstcp '1'

config service 'DynuNAS6'
	option service_name 'dynu.com'
	option enabled '1'
	option lookup_host 'nascn.ddnsfree.com'
	option use_ipv6 '1'
	option domain 'nascn.ddnsfree.com'
	option username 'sqmshcn'
	option password 'dynuddns'
	option ip_source 'web'
	option ip_url 'http://192.168.1.220:8080/ip6.html'
	option interface 'lan'
	option force_dnstcp '1'

config service 'DynuSSR6'
	option service_name 'dynu.com'
	option enabled '1'
	option lookup_host 'ssrcn.ddnsfree.com'
	option use_ipv6 '1'
	option domain 'ssrcn.ddnsfree.com'
	option username 'sqmshcn'
	option password 'dynuddns'
	option ip_source 'web'
	option ip_url 'http://192.168.1.110/ip6.html'
	option interface 'lan'
	option force_dnstcp '1'
EOF
}

if [ -f "/etc/init.d/smartdns" ]; then
	uci set smartdns.@smartdns[0].enabled='1'
	uci set smartdns.@smartdns[0].seconddns_enabled='0'
	uci set smartdns.@smartdns[0].port='53'
	uci commit smartdns
cat > /etc/smartdns/custom.conf <<EOF
# Add custom settings here.

# set log level
# log-level [level], level=fatal, error, warn, notice, info, debug
# log-level error

# log-size k,m,g
# log-size 128k

# log-file /var/log/smartdns.log
# log-num 2

# List of hosts that supply bogus NX domain results 
# bogus-nxdomain [ip/subnet]

#conf-file \/etc\/smartdns\/anti-ad-for-smartdns.conf
dnsmasq-lease-file /var/dhcp.leases
cache-size 1024
cache-persist yes
max-reply-ip-num 1
response-mode first-ping
prefetch-domain yes
tcp-idle-time 120
rr-ttl-min 60
rr-ttl-max 600
rr-ttl-reply-max 60
rr-ttl 600
local-ttl 60
speed-check-mode ping,tcp:80,tcp:443

server 119.29.29.29
server 114.114.114.114
server 223.5.5.5
server 2400:3200::1
EOF
fi

[ -f /etc/init.d/ttyd ] && {
cat > /etc/config/ttyd <<EOF
config ttyd
	option command '/bin/login'
	option debug '7'
	option ipv6 '1'
EOF
}

#sed -i '/dhcp-option/d' /etc/dnsmasq.conf
#echo "#dhcp-option-force=125,00:00:00:00:16:02:06:48:47:57:2d:43:54:03:04:5a:58:48:4e:0b:02:00:55:0a:02:20:00" >> /etc/dnsmasq.conf
#echo "#dhcp-option=15" >> /etc/dnsmasq.conf
#echo "#dhcp-option=28" >> /etc/dnsmasq.conf

sed -i 's/root::0:0:99999:7:::/root:$1$TADtMues$II9qrw8S7H3hYtJASm0tw.:19059:0:99999:7:::/g' /etc/shadow
sed -i '/option disabled/d' /etc/config/wireless
sed -i '/set wireless.radio${devidx}.disabled/d' /lib/wifi/mac80211.sh
wifi up

exit 0
